name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [8.4.0]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: docker-compose -f docker-compose-tests.yml up --exit-code-from pizza-express

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]

    permissions:
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pizza-express:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/pizza-express:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: gke-test-1
          location: europe-central2
          credentials: ${{ secrets.GCP_SA_KEY }}

      - run: kubectl get pods -A

      - uses: azure/setup-helm@v1
        id: install

      - run: helm upgrade --install -f helm-chart/values.yaml --set image.tag=${{ github.sha }} pizza-express helm-chart/
